"""Add CaseFinished table

Revision ID: b22873c78259
Revises: 
Create Date: 2024-08-18 10:15:48.945343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22873c78259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_processing')
    op.drop_table('user')
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.alter_column('protocolista_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('observaciones',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('idx_case_escritura')
        batch_op.drop_index('idx_case_fecha')
        batch_op.drop_index('idx_case_protocolista')
        batch_op.drop_constraint('fk_protocolista_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'protocolist', ['protocolista_id'], ['id'])
        batch_op.drop_column('protocolista')

    with op.batch_alter_table('case_finished', schema=None) as batch_op:
        batch_op.alter_column('protocolista',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('observaciones',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('protocolist', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('correo_electronico',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('radicado', schema=None) as batch_op:
        batch_op.alter_column('case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('radicado',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radicado', schema=None) as batch_op:
        batch_op.alter_column('radicado',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('case_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('protocolist', schema=None) as batch_op:
        batch_op.alter_column('correo_electronico',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('case_finished', schema=None) as batch_op:
        batch_op.alter_column('observaciones',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('protocolista',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocolista', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_protocolista_id', 'protocolist', ['protocolista_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('idx_case_protocolista', ['protocolista'], unique=False)
        batch_op.create_index('idx_case_fecha', ['fecha'], unique=False)
        batch_op.create_index('idx_case_escritura', ['escritura'], unique=False)
        batch_op.alter_column('observaciones',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('protocolista_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.create_table('case_processing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('escritura', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('radicado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('protocolista', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='case_processing_pkey')
    )
    # ### end Alembic commands ###
